version: "3.3"
services:
  web:
    image: tsari/heidisql
    restart: always
    environment:
      - DISPLAY
      - WINEPREFIX:/home/$USER/.wine32
    volumes:
      - /home/$USER:/home/$USER
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /etc/machine-id:/etc-machine-id:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
    working_dir: /home/$USER
    networks:
      - mdb
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
       - mdb

networks:
  mdb:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/24