version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: photos
      MYSQL_USER: iissi_user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080
