version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: grados
      MYSQL_USER: iissi_user
      MYSQL_PASSWORD: user

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080
   
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - DOCKER_MODS=linuxserver/mods:code-server-python
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PASSWORD=iissi_user 
      - SUDO_PASSWORD=thisisthepass
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - ./config:/config
      - ./workspace:/workspace
    ports:
      - 8443:8443
      - 8080:8080
    restart: unless-stopped
  
